# Generated by Django 4.2.4 on 2023-11-05 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0013_topuprequest_date_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuprequest',
            name='credited_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
